language: python
python:
    - "2.7"

cache:
    directories:
        - "~/.platformio"
git:
    submodules: false

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

install:
    - pip install -U platformio
    - platformio update

env:
    - BUILD_CONFIG=feedc0de_usb
    - BUILD_CONFIG=greyhash_usb
    - BUILD_CONFIG=aveexy_usb
    - BUILD_CONFIG=testbench_usb
    - BUILD_CONFIG=mickdermack_usb
    - BUILD_CONFIG=peter_usb

script:
    - platformio run -e $BUILD_CONFIG
