name: Build
on:
  push:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Userconfigs
    strategy:
      fail-fast: false
      matrix:
        node: [feedc0de, comred, peter, mick, nofeatures] # allfeatures not used here
    name: ${{ matrix.node }}
    steps:
    
      - name: Checkout (without submodules)
        uses: actions/checkout@v2

      - name: Checkout and install esp-idf
        uses: 0xFEEDC0DE64/checkout_install_esp_idf@main

      - name: Fast Submodule Checkout components/arduino-esp32
        uses: 0xFEEDC0DE64/fast_submodule_checkout@main
        with:
          submodule: components/arduino-esp32

      - name: Checkout remaining submodules
        run: git submodule update --init --recursive $(git submodule | awk '{ if ($2 != "esp-idf" && $2 != "components/arduino-esp32") print $2 }')

      - name: Setup ccache
        uses: 0xFEEDC0DE64/setup_ccache@main
        with:
          key: ${{ runner.os }}-ccache-${{ matrix.node }}

      - name: Unpack ignore folder
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
        run: |
          tools/bobby-decrypt
          
      - name: Build firmware
        run: |
          export CCACHE_MAXSIZE=400M CCACHE_BASEDIR="$(pwd)"
          . export.sh
          ./switchconf.sh ${{ matrix.node }}
          idf.py --ccache build
          ccache -s
          
      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: bobbyquad_${{ matrix.node }}
          path: |
            build_${{ matrix.node }}/bobbyquad_${{ matrix.node }}.bin
            build_${{ matrix.node }}/bobbyquad_${{ matrix.node }}.elf
            build_${{ matrix.node }}/bootloader/bootloader.bin
            build_${{ matrix.node }}/bootloader/bootloader.elf
            build_${{ matrix.node }}/partition_table/partition-table.bin
